### ISSUE TITLE
Test related code in setup.py should not work during install phase

### ISSUE THREAD

**Issue by DXist** [disqus/durabledict#9]
I get following error during durabledict 0.9.1 installation:

```
Downloading durabledict-0.9.1.tar.gz
  Storing download in cache at /home/jenkins/.pip/cache/https%3A%2F%2Fpypi.python.org%2Fpackages%2Fsource%2Fd%2Fdurabledict%2Fdurabledict-0.9.1.tar.gz
  Running setup.py (path:/usr/home/jenkins/.ve/madmin_ru/build/durabledict/setup.py) egg_info for package durabledict
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/usr/home/jenkins/.ve/madmin_ru/build/durabledict/setup.py", line 28, in <module>
        os.environ['ZOOKEEPER_PATH'] = get_zookeeper_paths()
      File "/usr/home/jenkins/.ve/madmin_ru/build/durabledict/setup.py", line 24, in get_zookeeper_paths
        raise Exception('ZOOKEEPER_PATH must be in environment for tests to run')
    Exception: ZOOKEEPER_PATH must be in environment for tests to run
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/usr/home/jenkins/.ve/madmin_ru/build/durabledict/setup.py", line 28, in <module>

    os.environ['ZOOKEEPER_PATH'] = get_zookeeper_paths()

  File "/usr/home/jenkins/.ve/madmin_ru/build/durabledict/setup.py", line 24, in get_zookeeper_paths

    raise Exception('ZOOKEEPER_PATH must be in environment for tests to run')

Exception: ZOOKEEPER_PATH must be in environment for tests to run
```

It can be reproduced in FreeBSD environment.

**Comment by brianz** [comment]
Just hit this same issue this morning.  Note this is also causing `pip install gutter` to fail.

**Comment by NorthIsUp** [comment]
a quick workaround is to set the ZOOKEEPER_PATH envvar. I'll look into why this is necessary.

**Comment by NorthIsUp** [comment]
I uploaded 0.9.2 which moves the requirement for ZOOKEEPER_PATH to the tests package. I was able to install the package from pip on os x. Please report back here if FreeBSD continues to fail.

**Comment by brianz** [comment]
:+1: 

Installs fine on CentOS too:

`pip install -e git+https://github.com/disqus/durabledict.git@be4b64ad`

Thanks for the quick fix.

**Comment by DXist** [comment]
0.9.2 installs fine on FreeBSD. Thank you!
